name: Example

on:
    pull_request:
    push:
        branches:
            - main
            - 'release/**'
        tags:
          - '*'

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests
